# Usa un'immagine di base con Python
FROM python:3.12-slim

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia il contenuto della cartella corrente nella cartella /app del container
COPY requirements.txt ./

# Installa le dipendenze
RUN 
RUN pip3 install -r requirements.txt 

# Copia il contenuto della cartella corrente nella cartella /app del container
COPY . .

# Esponi la porta su cui gira Flask (default 5000)
EXPOSE 5005

# Definisce il comando per avviare l'applicazione
CMD ["flask", "run", "--host=0.0.0.0", "--port=5005"]